/*
 * Fusion Wallet - A non-custodial cryptocurrency wallet
 * Copyright (C) 2025 Fusion Wallet
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 */


// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/canister.dart';
import 'api/cmc.dart';
import 'api/http_service.dart';
import 'api/ic_wallet_service.dart';
import 'api/nft_service.dart';
import 'api/simple.dart';
import 'api/wallet.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'lib.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_CyclesServicePtr => wire
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCyclesService;

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_HttpWalletServicePtr => wire
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHttpWalletService;

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_IcCanisterInfoServicePtr => wire
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerICCanisterInfoService;

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_IcCollectionServicePtr => wire
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerICCollectionService;

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_IcWalletServicePtr => wire
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerICWalletService;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_WalletPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWallet;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  CyclesService
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCyclesService(
          dynamic raw);

  @protected
  HttpWalletService
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHttpWalletService(
          dynamic raw);

  @protected
  IcCanisterInfoService
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerICCanisterInfoService(
          dynamic raw);

  @protected
  IcCollectionService
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerICCollectionService(
          dynamic raw);

  @protected
  IcWalletService
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerICWalletService(
          dynamic raw);

  @protected
  Wallet
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWallet(
          dynamic raw);

  @protected
  CyclesService
      dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCyclesService(
          dynamic raw);

  @protected
  HttpWalletService
      dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHttpWalletService(
          dynamic raw);

  @protected
  IcCanisterInfoService
      dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerICCanisterInfoService(
          dynamic raw);

  @protected
  IcCollectionService
      dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerICCollectionService(
          dynamic raw);

  @protected
  IcWalletService
      dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerICWalletService(
          dynamic raw);

  @protected
  Wallet
      dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWallet(
          dynamic raw);

  @protected
  BigInt dco_decode_I128(dynamic raw);

  @protected
  Map<String, CollectMetaValue> dco_decode_Map_String_collect_meta_value_None(
      dynamic raw);

  @protected
  CyclesService
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCyclesService(
          dynamic raw);

  @protected
  HttpWalletService
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHttpWalletService(
          dynamic raw);

  @protected
  IcCanisterInfoService
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerICCanisterInfoService(
          dynamic raw);

  @protected
  IcCollectionService
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerICCollectionService(
          dynamic raw);

  @protected
  IcWalletService
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerICWalletService(
          dynamic raw);

  @protected
  Wallet
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWallet(
          dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  IWalletService dco_decode_TraitDef_IWalletService(dynamic raw);

  @protected
  BigInt dco_decode_U128(dynamic raw);

  @protected
  AllowanceResponse dco_decode_allowance_response(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  double dco_decode_box_autoadd_f_64(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_8(dynamic raw);

  @protected
  WalletCollection dco_decode_box_autoadd_wallet_collection(dynamic raw);

  @protected
  WalletToken dco_decode_box_autoadd_wallet_token(dynamic raw);

  @protected
  CanisterMetric dco_decode_canister_metric(dynamic raw);

  @protected
  CollectMetaValue dco_decode_collect_meta_value(dynamic raw);

  @protected
  double dco_decode_f_32(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  GithubRelease dco_decode_github_release(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  IcpXdrConversionRate dco_decode_icp_xdr_conversion_rate(dynamic raw);

  @protected
  IcpXdrConversionRateResponse dco_decode_icp_xdr_conversion_rate_response(
      dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<(String, CollectMetaValue)>
      dco_decode_list_record_string_collect_meta_value(dynamic raw);

  @protected
  List<(BigInt, Map<String, CollectMetaValue>)>
      dco_decode_list_record_u_64_map_string_collect_meta_value_none(
          dynamic raw);

  @protected
  List<SimpleTransaction> dco_decode_list_simple_transaction(dynamic raw);

  @protected
  List<WalletToken> dco_decode_list_wallet_token(dynamic raw);

  @protected
  MintSuccess dco_decode_mint_success(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  double? dco_decode_opt_box_autoadd_f_64(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_8(dynamic raw);

  @protected
  Uint8List? dco_decode_opt_list_prim_u_8_strict(dynamic raw);

  @protected
  U8Array32? dco_decode_opt_u_8_array_32(dynamic raw);

  @protected
  QuoteResponse dco_decode_quote_response(dynamic raw);

  @protected
  (String, CollectMetaValue) dco_decode_record_string_collect_meta_value(
      dynamic raw);

  @protected
  (BigInt, Map<String, CollectMetaValue>)
      dco_decode_record_u_64_map_string_collect_meta_value_none(dynamic raw);

  @protected
  SimpleTransaction dco_decode_simple_transaction(dynamic raw);

  @protected
  SwapResponse dco_decode_swap_response(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  U8Array32 dco_decode_u_8_array_32(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  WalletCollection dco_decode_wallet_collection(dynamic raw);

  @protected
  WalletContext dco_decode_wallet_context(dynamic raw);

  @protected
  WalletToken dco_decode_wallet_token(dynamic raw);

  @protected
  WalletTokenNetWork dco_decode_wallet_token_net_work(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  CyclesService
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCyclesService(
          SseDeserializer deserializer);

  @protected
  HttpWalletService
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHttpWalletService(
          SseDeserializer deserializer);

  @protected
  IcCanisterInfoService
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerICCanisterInfoService(
          SseDeserializer deserializer);

  @protected
  IcCollectionService
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerICCollectionService(
          SseDeserializer deserializer);

  @protected
  IcWalletService
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerICWalletService(
          SseDeserializer deserializer);

  @protected
  Wallet
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWallet(
          SseDeserializer deserializer);

  @protected
  CyclesService
      sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCyclesService(
          SseDeserializer deserializer);

  @protected
  HttpWalletService
      sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHttpWalletService(
          SseDeserializer deserializer);

  @protected
  IcCanisterInfoService
      sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerICCanisterInfoService(
          SseDeserializer deserializer);

  @protected
  IcCollectionService
      sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerICCollectionService(
          SseDeserializer deserializer);

  @protected
  IcWalletService
      sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerICWalletService(
          SseDeserializer deserializer);

  @protected
  Wallet
      sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWallet(
          SseDeserializer deserializer);

  @protected
  BigInt sse_decode_I128(SseDeserializer deserializer);

  @protected
  Map<String, CollectMetaValue> sse_decode_Map_String_collect_meta_value_None(
      SseDeserializer deserializer);

  @protected
  CyclesService
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCyclesService(
          SseDeserializer deserializer);

  @protected
  HttpWalletService
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHttpWalletService(
          SseDeserializer deserializer);

  @protected
  IcCanisterInfoService
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerICCanisterInfoService(
          SseDeserializer deserializer);

  @protected
  IcCollectionService
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerICCollectionService(
          SseDeserializer deserializer);

  @protected
  IcWalletService
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerICWalletService(
          SseDeserializer deserializer);

  @protected
  Wallet
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWallet(
          SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_U128(SseDeserializer deserializer);

  @protected
  AllowanceResponse sse_decode_allowance_response(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  double sse_decode_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_u_8(SseDeserializer deserializer);

  @protected
  WalletCollection sse_decode_box_autoadd_wallet_collection(
      SseDeserializer deserializer);

  @protected
  WalletToken sse_decode_box_autoadd_wallet_token(SseDeserializer deserializer);

  @protected
  CanisterMetric sse_decode_canister_metric(SseDeserializer deserializer);

  @protected
  CollectMetaValue sse_decode_collect_meta_value(SseDeserializer deserializer);

  @protected
  double sse_decode_f_32(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  GithubRelease sse_decode_github_release(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  IcpXdrConversionRate sse_decode_icp_xdr_conversion_rate(
      SseDeserializer deserializer);

  @protected
  IcpXdrConversionRateResponse sse_decode_icp_xdr_conversion_rate_response(
      SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<(String, CollectMetaValue)>
      sse_decode_list_record_string_collect_meta_value(
          SseDeserializer deserializer);

  @protected
  List<(BigInt, Map<String, CollectMetaValue>)>
      sse_decode_list_record_u_64_map_string_collect_meta_value_none(
          SseDeserializer deserializer);

  @protected
  List<SimpleTransaction> sse_decode_list_simple_transaction(
      SseDeserializer deserializer);

  @protected
  List<WalletToken> sse_decode_list_wallet_token(SseDeserializer deserializer);

  @protected
  MintSuccess sse_decode_mint_success(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  double? sse_decode_opt_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_u_8(SseDeserializer deserializer);

  @protected
  Uint8List? sse_decode_opt_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  U8Array32? sse_decode_opt_u_8_array_32(SseDeserializer deserializer);

  @protected
  QuoteResponse sse_decode_quote_response(SseDeserializer deserializer);

  @protected
  (String, CollectMetaValue) sse_decode_record_string_collect_meta_value(
      SseDeserializer deserializer);

  @protected
  (BigInt, Map<String, CollectMetaValue>)
      sse_decode_record_u_64_map_string_collect_meta_value_none(
          SseDeserializer deserializer);

  @protected
  SimpleTransaction sse_decode_simple_transaction(SseDeserializer deserializer);

  @protected
  SwapResponse sse_decode_swap_response(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  U8Array32 sse_decode_u_8_array_32(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  WalletCollection sse_decode_wallet_collection(SseDeserializer deserializer);

  @protected
  WalletContext sse_decode_wallet_context(SseDeserializer deserializer);

  @protected
  WalletToken sse_decode_wallet_token(SseDeserializer deserializer);

  @protected
  WalletTokenNetWork sse_decode_wallet_token_net_work(
      SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
      AnyhowException self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCyclesService(
          CyclesService self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHttpWalletService(
          HttpWalletService self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerICCanisterInfoService(
          IcCanisterInfoService self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerICCollectionService(
          IcCollectionService self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerICWalletService(
          IcWalletService self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWallet(
          Wallet self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCyclesService(
          CyclesService self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHttpWalletService(
          HttpWalletService self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerICCanisterInfoService(
          IcCanisterInfoService self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerICCollectionService(
          IcCollectionService self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerICWalletService(
          IcWalletService self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWallet(
          Wallet self, SseSerializer serializer);

  @protected
  void sse_encode_I128(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_Map_String_collect_meta_value_None(
      Map<String, CollectMetaValue> self, SseSerializer serializer);

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCyclesService(
          CyclesService self, SseSerializer serializer);

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHttpWalletService(
          HttpWalletService self, SseSerializer serializer);

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerICCanisterInfoService(
          IcCanisterInfoService self, SseSerializer serializer);

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerICCollectionService(
          IcCollectionService self, SseSerializer serializer);

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerICWalletService(
          IcWalletService self, SseSerializer serializer);

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWallet(
          Wallet self, SseSerializer serializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_U128(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_allowance_response(
      AllowanceResponse self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_wallet_collection(
      WalletCollection self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_wallet_token(
      WalletToken self, SseSerializer serializer);

  @protected
  void sse_encode_canister_metric(
      CanisterMetric self, SseSerializer serializer);

  @protected
  void sse_encode_collect_meta_value(
      CollectMetaValue self, SseSerializer serializer);

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_github_release(GithubRelease self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_icp_xdr_conversion_rate(
      IcpXdrConversionRate self, SseSerializer serializer);

  @protected
  void sse_encode_icp_xdr_conversion_rate_response(
      IcpXdrConversionRateResponse self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer);

  @protected
  void sse_encode_list_record_string_collect_meta_value(
      List<(String, CollectMetaValue)> self, SseSerializer serializer);

  @protected
  void sse_encode_list_record_u_64_map_string_collect_meta_value_none(
      List<(BigInt, Map<String, CollectMetaValue>)> self,
      SseSerializer serializer);

  @protected
  void sse_encode_list_simple_transaction(
      List<SimpleTransaction> self, SseSerializer serializer);

  @protected
  void sse_encode_list_wallet_token(
      List<WalletToken> self, SseSerializer serializer);

  @protected
  void sse_encode_mint_success(MintSuccess self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_f_64(double? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_8(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_list_prim_u_8_strict(
      Uint8List? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_u_8_array_32(U8Array32? self, SseSerializer serializer);

  @protected
  void sse_encode_quote_response(QuoteResponse self, SseSerializer serializer);

  @protected
  void sse_encode_record_string_collect_meta_value(
      (String, CollectMetaValue) self, SseSerializer serializer);

  @protected
  void sse_encode_record_u_64_map_string_collect_meta_value_none(
      (BigInt, Map<String, CollectMetaValue>) self, SseSerializer serializer);

  @protected
  void sse_encode_simple_transaction(
      SimpleTransaction self, SseSerializer serializer);

  @protected
  void sse_encode_swap_response(SwapResponse self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8_array_32(U8Array32 self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_wallet_collection(
      WalletCollection self, SseSerializer serializer);

  @protected
  void sse_encode_wallet_context(WalletContext self, SseSerializer serializer);

  @protected
  void sse_encode_wallet_token(WalletToken self, SseSerializer serializer);

  @protected
  void sse_encode_wallet_token_net_work(
      WalletTokenNetWork self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);

  void rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCyclesService(
          int ptr) =>
      wasmModule
          .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCyclesService(
              ptr);

  void rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCyclesService(
          int ptr) =>
      wasmModule
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCyclesService(
              ptr);

  void rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHttpWalletService(
          int ptr) =>
      wasmModule
          .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHttpWalletService(
              ptr);

  void rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHttpWalletService(
          int ptr) =>
      wasmModule
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHttpWalletService(
              ptr);

  void rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerICCanisterInfoService(
          int ptr) =>
      wasmModule
          .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerICCanisterInfoService(
              ptr);

  void rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerICCanisterInfoService(
          int ptr) =>
      wasmModule
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerICCanisterInfoService(
              ptr);

  void rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerICCollectionService(
          int ptr) =>
      wasmModule
          .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerICCollectionService(
              ptr);

  void rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerICCollectionService(
          int ptr) =>
      wasmModule
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerICCollectionService(
              ptr);

  void rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerICWalletService(
          int ptr) =>
      wasmModule
          .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerICWalletService(
              ptr);

  void rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerICWalletService(
          int ptr) =>
      wasmModule
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerICWalletService(
              ptr);

  void rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWallet(
          int ptr) =>
      wasmModule
          .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWallet(
              ptr);

  void rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWallet(
          int ptr) =>
      wasmModule
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWallet(
              ptr);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {
  external void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCyclesService(
          int ptr);

  external void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCyclesService(
          int ptr);

  external void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHttpWalletService(
          int ptr);

  external void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHttpWalletService(
          int ptr);

  external void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerICCanisterInfoService(
          int ptr);

  external void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerICCanisterInfoService(
          int ptr);

  external void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerICCollectionService(
          int ptr);

  external void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerICCollectionService(
          int ptr);

  external void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerICWalletService(
          int ptr);

  external void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerICWalletService(
          int ptr);

  external void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWallet(
          int ptr);

  external void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWallet(
          int ptr);
}
