// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.7.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/simple.dart';
import 'api/utils.dart';
import 'api/wallet.dart';
import 'api/wallet_service.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({
    required RustLibApi api,
  }) {
    instance.initMockImpl(
      api: api,
    );
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.7.0';

  @override
  int get rustContentHash => 604072633;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
    stem: 'rust_lib_fusion_wallet',
    ioDirectory: 'rust/target/release/',
    webPrefix: 'pkg/',
  );
}

abstract class RustLibApi extends BaseApi {
  Future<BigInt> crateApiWalletServiceIcWalletServiceApprove(
      {required IcWalletService that,
      required WalletToken token,
      required String spender,
      required BigInt amount});

  Future<BigInt> crateApiWalletServiceIcWalletServiceGetAllowance(
      {required IcWalletService that,
      required WalletToken token,
      required String owner,
      required String spender});

  Future<BigInt> crateApiWalletServiceIcWalletServiceGetBalance(
      {required IcWalletService that,
      required WalletToken token,
      required String account});

  Future<List<SimpleTransaction>>
      crateApiWalletServiceIcWalletServiceGetLatestTransactions(
          {required IcWalletService that,
          required WalletToken token,
          required String accountAddr,
          int? maxResults});

  Future<double> crateApiWalletServiceIcWalletServiceGetPrice(
      {required IcWalletService that, required WalletToken token});

  Future<WalletToken> crateApiWalletServiceIcWalletServiceGetToken(
      {required IcWalletService that,
      required String canisterId,
      String? indexCanister});

  Future<BigInt> crateApiWalletServiceIcWalletServiceSend(
      {required IcWalletService that,
      required WalletToken token,
      required String to,
      required BigInt amount});

  Future<QuoteResponse> crateApiWalletServiceIcWalletServiceSwapQuote(
      {required IcWalletService that,
      required WalletToken payToken,
      required WalletToken receiveToken,
      required BigInt payAmount});

  Future<TokenMetadata> crateApiUtilsTokenMetadataDefault();

  String? crateApiWalletWalletTokenAutoAccessorGetGovCanister(
      {required WalletToken that});

  String? crateApiWalletWalletTokenAutoAccessorGetImageUrl(
      {required WalletToken that});

  String? crateApiWalletWalletTokenAutoAccessorGetIndexCanister(
      {required WalletToken that});

  WalletTokenNetWork crateApiWalletWalletTokenAutoAccessorGetNetwork(
      {required WalletToken that});

  String crateApiWalletWalletTokenAutoAccessorGetSymbol(
      {required WalletToken that});

  String crateApiWalletWalletTokenAutoAccessorGetTokenAddress(
      {required WalletToken that});

  int? crateApiWalletWalletTokenAutoAccessorGetTokenDecimal(
      {required WalletToken that});

  String crateApiWalletWalletTokenAutoAccessorGetTokenName(
      {required WalletToken that});

  BigInt crateApiWalletWalletTokenAutoAccessorGetTransferFee(
      {required WalletToken that});

  void crateApiWalletWalletTokenAutoAccessorSetGovCanister(
      {required WalletToken that, String? govCanister});

  void crateApiWalletWalletTokenAutoAccessorSetImageUrl(
      {required WalletToken that, String? imageUrl});

  void crateApiWalletWalletTokenAutoAccessorSetIndexCanister(
      {required WalletToken that, String? indexCanister});

  void crateApiWalletWalletTokenAutoAccessorSetNetwork(
      {required WalletToken that, required WalletTokenNetWork network});

  void crateApiWalletWalletTokenAutoAccessorSetSymbol(
      {required WalletToken that, required String symbol});

  void crateApiWalletWalletTokenAutoAccessorSetTokenAddress(
      {required WalletToken that, required String tokenAddress});

  void crateApiWalletWalletTokenAutoAccessorSetTokenDecimal(
      {required WalletToken that, int? tokenDecimal});

  void crateApiWalletWalletTokenAutoAccessorSetTokenName(
      {required WalletToken that, required String tokenName});

  void crateApiWalletWalletTokenAutoAccessorSetTransferFee(
      {required WalletToken that, required BigInt transferFee});

  WalletToken crateApiWalletWalletTokenFromString({required String data});

  String crateApiWalletWalletTokenToString({required WalletToken that});

  Wallet crateApiWalletWalletCreateChildWallet(
      {required Wallet that, required String path});

  IcWalletService crateApiWalletWalletCreateIcService({required Wallet that});

  Wallet crateApiWalletWalletFromSeed({required String seedPhrase});

  Uint8List crateApiWalletWalletSignMessage(
      {required Wallet that, required List<int> message});

  String crateApiWalletWalletToAccountIdentifier({required Wallet that});

  String crateApiWalletWalletToBitcoinAddress({required Wallet that});

  String crateApiWalletWalletToIcpPrincipal({required Wallet that});

  Future<String> crateApiWalletGenerateSeedPhrase();

  String crateApiSimpleGreet({required String name});

  Future<void> crateApiSimpleInitApp();

  List<WalletToken> crateApiWalletWalletContextGetAllSupportedTokens();

  List<WalletToken> crateApiWalletWalletContextGetInitialSupportedTokens();

  String crateApiWalletWalletContextHashData({required String data});

  bool crateApiWalletWalletContextVerifyMnemonic({required String mnemonic});

  bool crateApiWalletWalletContextVerifyPrincipal({required String text});

  RustArcIncrementStrongCountFnType
      get rust_arc_increment_strong_count_IcWalletService;

  RustArcDecrementStrongCountFnType
      get rust_arc_decrement_strong_count_IcWalletService;

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_IcWalletServicePtr;

  RustArcIncrementStrongCountFnType
      get rust_arc_increment_strong_count_TokenMetadata;

  RustArcDecrementStrongCountFnType
      get rust_arc_decrement_strong_count_TokenMetadata;

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_TokenMetadataPtr;

  RustArcIncrementStrongCountFnType get rust_arc_increment_strong_count_Wallet;

  RustArcDecrementStrongCountFnType get rust_arc_decrement_strong_count_Wallet;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_WalletPtr;

  RustArcIncrementStrongCountFnType
      get rust_arc_increment_strong_count_WalletToken;

  RustArcDecrementStrongCountFnType
      get rust_arc_decrement_strong_count_WalletToken;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_WalletTokenPtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<BigInt> crateApiWalletServiceIcWalletServiceApprove(
      {required IcWalletService that,
      required WalletToken token,
      required String spender,
      required BigInt amount}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerICWalletService(
            that, serializer);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWalletToken(
            token, serializer);
        sse_encode_String(spender, serializer);
        sse_encode_u_64(amount, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 1, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_u_64,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiWalletServiceIcWalletServiceApproveConstMeta,
      argValues: [that, token, spender, amount],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiWalletServiceIcWalletServiceApproveConstMeta =>
      const TaskConstMeta(
        debugName: "IcWalletService_approve",
        argNames: ["that", "token", "spender", "amount"],
      );

  @override
  Future<BigInt> crateApiWalletServiceIcWalletServiceGetAllowance(
      {required IcWalletService that,
      required WalletToken token,
      required String owner,
      required String spender}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerICWalletService(
            that, serializer);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWalletToken(
            token, serializer);
        sse_encode_String(owner, serializer);
        sse_encode_String(spender, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 2, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_u_64,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiWalletServiceIcWalletServiceGetAllowanceConstMeta,
      argValues: [that, token, owner, spender],
      apiImpl: this,
    ));
  }

  TaskConstMeta
      get kCrateApiWalletServiceIcWalletServiceGetAllowanceConstMeta =>
          const TaskConstMeta(
            debugName: "IcWalletService_get_allowance",
            argNames: ["that", "token", "owner", "spender"],
          );

  @override
  Future<BigInt> crateApiWalletServiceIcWalletServiceGetBalance(
      {required IcWalletService that,
      required WalletToken token,
      required String account}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerICWalletService(
            that, serializer);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWalletToken(
            token, serializer);
        sse_encode_String(account, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 3, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_u_64,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiWalletServiceIcWalletServiceGetBalanceConstMeta,
      argValues: [that, token, account],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiWalletServiceIcWalletServiceGetBalanceConstMeta =>
      const TaskConstMeta(
        debugName: "IcWalletService_get_balance",
        argNames: ["that", "token", "account"],
      );

  @override
  Future<List<SimpleTransaction>>
      crateApiWalletServiceIcWalletServiceGetLatestTransactions(
          {required IcWalletService that,
          required WalletToken token,
          required String accountAddr,
          int? maxResults}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerICWalletService(
            that, serializer);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWalletToken(
            token, serializer);
        sse_encode_String(accountAddr, serializer);
        sse_encode_opt_box_autoadd_u_32(maxResults, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 4, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_simple_transaction,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta:
          kCrateApiWalletServiceIcWalletServiceGetLatestTransactionsConstMeta,
      argValues: [that, token, accountAddr, maxResults],
      apiImpl: this,
    ));
  }

  TaskConstMeta
      get kCrateApiWalletServiceIcWalletServiceGetLatestTransactionsConstMeta =>
          const TaskConstMeta(
            debugName: "IcWalletService_get_latest_transactions",
            argNames: ["that", "token", "accountAddr", "maxResults"],
          );

  @override
  Future<double> crateApiWalletServiceIcWalletServiceGetPrice(
      {required IcWalletService that, required WalletToken token}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerICWalletService(
            that, serializer);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWalletToken(
            token, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 5, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_f_32,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiWalletServiceIcWalletServiceGetPriceConstMeta,
      argValues: [that, token],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiWalletServiceIcWalletServiceGetPriceConstMeta =>
      const TaskConstMeta(
        debugName: "IcWalletService_get_price",
        argNames: ["that", "token"],
      );

  @override
  Future<WalletToken> crateApiWalletServiceIcWalletServiceGetToken(
      {required IcWalletService that,
      required String canisterId,
      String? indexCanister}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerICWalletService(
            that, serializer);
        sse_encode_String(canisterId, serializer);
        sse_encode_opt_String(indexCanister, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 6, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData:
            sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWalletToken,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiWalletServiceIcWalletServiceGetTokenConstMeta,
      argValues: [that, canisterId, indexCanister],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiWalletServiceIcWalletServiceGetTokenConstMeta =>
      const TaskConstMeta(
        debugName: "IcWalletService_get_token",
        argNames: ["that", "canisterId", "indexCanister"],
      );

  @override
  Future<BigInt> crateApiWalletServiceIcWalletServiceSend(
      {required IcWalletService that,
      required WalletToken token,
      required String to,
      required BigInt amount}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerICWalletService(
            that, serializer);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWalletToken(
            token, serializer);
        sse_encode_String(to, serializer);
        sse_encode_u_64(amount, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 7, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_u_64,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiWalletServiceIcWalletServiceSendConstMeta,
      argValues: [that, token, to, amount],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiWalletServiceIcWalletServiceSendConstMeta =>
      const TaskConstMeta(
        debugName: "IcWalletService_send",
        argNames: ["that", "token", "to", "amount"],
      );

  @override
  Future<QuoteResponse> crateApiWalletServiceIcWalletServiceSwapQuote(
      {required IcWalletService that,
      required WalletToken payToken,
      required WalletToken receiveToken,
      required BigInt payAmount}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerICWalletService(
            that, serializer);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWalletToken(
            payToken, serializer);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWalletToken(
            receiveToken, serializer);
        sse_encode_u_64(payAmount, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 8, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_quote_response,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiWalletServiceIcWalletServiceSwapQuoteConstMeta,
      argValues: [that, payToken, receiveToken, payAmount],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiWalletServiceIcWalletServiceSwapQuoteConstMeta =>
      const TaskConstMeta(
        debugName: "IcWalletService_swap_quote",
        argNames: ["that", "payToken", "receiveToken", "payAmount"],
      );

  @override
  Future<TokenMetadata> crateApiUtilsTokenMetadataDefault() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 9, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData:
            sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTokenMetadata,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiUtilsTokenMetadataDefaultConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiUtilsTokenMetadataDefaultConstMeta =>
      const TaskConstMeta(
        debugName: "TokenMetadata_default",
        argNames: [],
      );

  @override
  String? crateApiWalletWalletTokenAutoAccessorGetGovCanister(
      {required WalletToken that}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWalletToken(
            that, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 12)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_opt_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiWalletWalletTokenAutoAccessorGetGovCanisterConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta
      get kCrateApiWalletWalletTokenAutoAccessorGetGovCanisterConstMeta =>
          const TaskConstMeta(
            debugName: "WalletToken_auto_accessor_get_gov_canister",
            argNames: ["that"],
          );

  @override
  String? crateApiWalletWalletTokenAutoAccessorGetImageUrl(
      {required WalletToken that}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWalletToken(
            that, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 13)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_opt_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiWalletWalletTokenAutoAccessorGetImageUrlConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta
      get kCrateApiWalletWalletTokenAutoAccessorGetImageUrlConstMeta =>
          const TaskConstMeta(
            debugName: "WalletToken_auto_accessor_get_image_url",
            argNames: ["that"],
          );

  @override
  String? crateApiWalletWalletTokenAutoAccessorGetIndexCanister(
      {required WalletToken that}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWalletToken(
            that, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 14)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_opt_String,
        decodeErrorData: null,
      ),
      constMeta:
          kCrateApiWalletWalletTokenAutoAccessorGetIndexCanisterConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta
      get kCrateApiWalletWalletTokenAutoAccessorGetIndexCanisterConstMeta =>
          const TaskConstMeta(
            debugName: "WalletToken_auto_accessor_get_index_canister",
            argNames: ["that"],
          );

  @override
  WalletTokenNetWork crateApiWalletWalletTokenAutoAccessorGetNetwork(
      {required WalletToken that}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWalletToken(
            that, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 15)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_wallet_token_net_work,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiWalletWalletTokenAutoAccessorGetNetworkConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiWalletWalletTokenAutoAccessorGetNetworkConstMeta =>
      const TaskConstMeta(
        debugName: "WalletToken_auto_accessor_get_network",
        argNames: ["that"],
      );

  @override
  String crateApiWalletWalletTokenAutoAccessorGetSymbol(
      {required WalletToken that}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWalletToken(
            that, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 16)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiWalletWalletTokenAutoAccessorGetSymbolConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiWalletWalletTokenAutoAccessorGetSymbolConstMeta =>
      const TaskConstMeta(
        debugName: "WalletToken_auto_accessor_get_symbol",
        argNames: ["that"],
      );

  @override
  String crateApiWalletWalletTokenAutoAccessorGetTokenAddress(
      {required WalletToken that}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWalletToken(
            that, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 17)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiWalletWalletTokenAutoAccessorGetTokenAddressConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta
      get kCrateApiWalletWalletTokenAutoAccessorGetTokenAddressConstMeta =>
          const TaskConstMeta(
            debugName: "WalletToken_auto_accessor_get_token_address",
            argNames: ["that"],
          );

  @override
  int? crateApiWalletWalletTokenAutoAccessorGetTokenDecimal(
      {required WalletToken that}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWalletToken(
            that, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 18)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_opt_box_autoadd_u_8,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiWalletWalletTokenAutoAccessorGetTokenDecimalConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta
      get kCrateApiWalletWalletTokenAutoAccessorGetTokenDecimalConstMeta =>
          const TaskConstMeta(
            debugName: "WalletToken_auto_accessor_get_token_decimal",
            argNames: ["that"],
          );

  @override
  String crateApiWalletWalletTokenAutoAccessorGetTokenName(
      {required WalletToken that}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWalletToken(
            that, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 19)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiWalletWalletTokenAutoAccessorGetTokenNameConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta
      get kCrateApiWalletWalletTokenAutoAccessorGetTokenNameConstMeta =>
          const TaskConstMeta(
            debugName: "WalletToken_auto_accessor_get_token_name",
            argNames: ["that"],
          );

  @override
  BigInt crateApiWalletWalletTokenAutoAccessorGetTransferFee(
      {required WalletToken that}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWalletToken(
            that, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 20)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_U128,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiWalletWalletTokenAutoAccessorGetTransferFeeConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta
      get kCrateApiWalletWalletTokenAutoAccessorGetTransferFeeConstMeta =>
          const TaskConstMeta(
            debugName: "WalletToken_auto_accessor_get_transfer_fee",
            argNames: ["that"],
          );

  @override
  void crateApiWalletWalletTokenAutoAccessorSetGovCanister(
      {required WalletToken that, String? govCanister}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWalletToken(
            that, serializer);
        sse_encode_opt_String(govCanister, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 21)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiWalletWalletTokenAutoAccessorSetGovCanisterConstMeta,
      argValues: [that, govCanister],
      apiImpl: this,
    ));
  }

  TaskConstMeta
      get kCrateApiWalletWalletTokenAutoAccessorSetGovCanisterConstMeta =>
          const TaskConstMeta(
            debugName: "WalletToken_auto_accessor_set_gov_canister",
            argNames: ["that", "govCanister"],
          );

  @override
  void crateApiWalletWalletTokenAutoAccessorSetImageUrl(
      {required WalletToken that, String? imageUrl}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWalletToken(
            that, serializer);
        sse_encode_opt_String(imageUrl, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 22)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiWalletWalletTokenAutoAccessorSetImageUrlConstMeta,
      argValues: [that, imageUrl],
      apiImpl: this,
    ));
  }

  TaskConstMeta
      get kCrateApiWalletWalletTokenAutoAccessorSetImageUrlConstMeta =>
          const TaskConstMeta(
            debugName: "WalletToken_auto_accessor_set_image_url",
            argNames: ["that", "imageUrl"],
          );

  @override
  void crateApiWalletWalletTokenAutoAccessorSetIndexCanister(
      {required WalletToken that, String? indexCanister}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWalletToken(
            that, serializer);
        sse_encode_opt_String(indexCanister, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 23)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta:
          kCrateApiWalletWalletTokenAutoAccessorSetIndexCanisterConstMeta,
      argValues: [that, indexCanister],
      apiImpl: this,
    ));
  }

  TaskConstMeta
      get kCrateApiWalletWalletTokenAutoAccessorSetIndexCanisterConstMeta =>
          const TaskConstMeta(
            debugName: "WalletToken_auto_accessor_set_index_canister",
            argNames: ["that", "indexCanister"],
          );

  @override
  void crateApiWalletWalletTokenAutoAccessorSetNetwork(
      {required WalletToken that, required WalletTokenNetWork network}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWalletToken(
            that, serializer);
        sse_encode_wallet_token_net_work(network, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 24)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiWalletWalletTokenAutoAccessorSetNetworkConstMeta,
      argValues: [that, network],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiWalletWalletTokenAutoAccessorSetNetworkConstMeta =>
      const TaskConstMeta(
        debugName: "WalletToken_auto_accessor_set_network",
        argNames: ["that", "network"],
      );

  @override
  void crateApiWalletWalletTokenAutoAccessorSetSymbol(
      {required WalletToken that, required String symbol}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWalletToken(
            that, serializer);
        sse_encode_String(symbol, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 25)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiWalletWalletTokenAutoAccessorSetSymbolConstMeta,
      argValues: [that, symbol],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiWalletWalletTokenAutoAccessorSetSymbolConstMeta =>
      const TaskConstMeta(
        debugName: "WalletToken_auto_accessor_set_symbol",
        argNames: ["that", "symbol"],
      );

  @override
  void crateApiWalletWalletTokenAutoAccessorSetTokenAddress(
      {required WalletToken that, required String tokenAddress}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWalletToken(
            that, serializer);
        sse_encode_String(tokenAddress, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 26)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiWalletWalletTokenAutoAccessorSetTokenAddressConstMeta,
      argValues: [that, tokenAddress],
      apiImpl: this,
    ));
  }

  TaskConstMeta
      get kCrateApiWalletWalletTokenAutoAccessorSetTokenAddressConstMeta =>
          const TaskConstMeta(
            debugName: "WalletToken_auto_accessor_set_token_address",
            argNames: ["that", "tokenAddress"],
          );

  @override
  void crateApiWalletWalletTokenAutoAccessorSetTokenDecimal(
      {required WalletToken that, int? tokenDecimal}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWalletToken(
            that, serializer);
        sse_encode_opt_box_autoadd_u_8(tokenDecimal, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 27)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiWalletWalletTokenAutoAccessorSetTokenDecimalConstMeta,
      argValues: [that, tokenDecimal],
      apiImpl: this,
    ));
  }

  TaskConstMeta
      get kCrateApiWalletWalletTokenAutoAccessorSetTokenDecimalConstMeta =>
          const TaskConstMeta(
            debugName: "WalletToken_auto_accessor_set_token_decimal",
            argNames: ["that", "tokenDecimal"],
          );

  @override
  void crateApiWalletWalletTokenAutoAccessorSetTokenName(
      {required WalletToken that, required String tokenName}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWalletToken(
            that, serializer);
        sse_encode_String(tokenName, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 28)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiWalletWalletTokenAutoAccessorSetTokenNameConstMeta,
      argValues: [that, tokenName],
      apiImpl: this,
    ));
  }

  TaskConstMeta
      get kCrateApiWalletWalletTokenAutoAccessorSetTokenNameConstMeta =>
          const TaskConstMeta(
            debugName: "WalletToken_auto_accessor_set_token_name",
            argNames: ["that", "tokenName"],
          );

  @override
  void crateApiWalletWalletTokenAutoAccessorSetTransferFee(
      {required WalletToken that, required BigInt transferFee}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWalletToken(
            that, serializer);
        sse_encode_U128(transferFee, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 29)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiWalletWalletTokenAutoAccessorSetTransferFeeConstMeta,
      argValues: [that, transferFee],
      apiImpl: this,
    ));
  }

  TaskConstMeta
      get kCrateApiWalletWalletTokenAutoAccessorSetTransferFeeConstMeta =>
          const TaskConstMeta(
            debugName: "WalletToken_auto_accessor_set_transfer_fee",
            argNames: ["that", "transferFee"],
          );

  @override
  WalletToken crateApiWalletWalletTokenFromString({required String data}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(data, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 30)!;
      },
      codec: SseCodec(
        decodeSuccessData:
            sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWalletToken,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiWalletWalletTokenFromStringConstMeta,
      argValues: [data],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiWalletWalletTokenFromStringConstMeta =>
      const TaskConstMeta(
        debugName: "WalletToken_from_string",
        argNames: ["data"],
      );

  @override
  String crateApiWalletWalletTokenToString({required WalletToken that}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWalletToken(
            that, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 31)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiWalletWalletTokenToStringConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiWalletWalletTokenToStringConstMeta =>
      const TaskConstMeta(
        debugName: "WalletToken_to_string",
        argNames: ["that"],
      );

  @override
  Wallet crateApiWalletWalletCreateChildWallet(
      {required Wallet that, required String path}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWallet(
            that, serializer);
        sse_encode_String(path, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 32)!;
      },
      codec: SseCodec(
        decodeSuccessData:
            sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWallet,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiWalletWalletCreateChildWalletConstMeta,
      argValues: [that, path],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiWalletWalletCreateChildWalletConstMeta =>
      const TaskConstMeta(
        debugName: "Wallet_create_child_wallet",
        argNames: ["that", "path"],
      );

  @override
  IcWalletService crateApiWalletWalletCreateIcService({required Wallet that}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWallet(
            that, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 33)!;
      },
      codec: SseCodec(
        decodeSuccessData:
            sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerICWalletService,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiWalletWalletCreateIcServiceConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiWalletWalletCreateIcServiceConstMeta =>
      const TaskConstMeta(
        debugName: "Wallet_create_ic_service",
        argNames: ["that"],
      );

  @override
  Wallet crateApiWalletWalletFromSeed({required String seedPhrase}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(seedPhrase, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 34)!;
      },
      codec: SseCodec(
        decodeSuccessData:
            sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWallet,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiWalletWalletFromSeedConstMeta,
      argValues: [seedPhrase],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiWalletWalletFromSeedConstMeta =>
      const TaskConstMeta(
        debugName: "Wallet_from_seed",
        argNames: ["seedPhrase"],
      );

  @override
  Uint8List crateApiWalletWalletSignMessage(
      {required Wallet that, required List<int> message}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWallet(
            that, serializer);
        sse_encode_list_prim_u_8_loose(message, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 35)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_prim_u_8_strict,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiWalletWalletSignMessageConstMeta,
      argValues: [that, message],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiWalletWalletSignMessageConstMeta =>
      const TaskConstMeta(
        debugName: "Wallet_sign_message",
        argNames: ["that", "message"],
      );

  @override
  String crateApiWalletWalletToAccountIdentifier({required Wallet that}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWallet(
            that, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 36)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiWalletWalletToAccountIdentifierConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiWalletWalletToAccountIdentifierConstMeta =>
      const TaskConstMeta(
        debugName: "Wallet_to_account_identifier",
        argNames: ["that"],
      );

  @override
  String crateApiWalletWalletToBitcoinAddress({required Wallet that}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWallet(
            that, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 37)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiWalletWalletToBitcoinAddressConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiWalletWalletToBitcoinAddressConstMeta =>
      const TaskConstMeta(
        debugName: "Wallet_to_bitcoin_address",
        argNames: ["that"],
      );

  @override
  String crateApiWalletWalletToIcpPrincipal({required Wallet that}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWallet(
            that, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 38)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiWalletWalletToIcpPrincipalConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiWalletWalletToIcpPrincipalConstMeta =>
      const TaskConstMeta(
        debugName: "Wallet_to_icp_principal",
        argNames: ["that"],
      );

  @override
  Future<String> crateApiWalletGenerateSeedPhrase() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 39, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiWalletGenerateSeedPhraseConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiWalletGenerateSeedPhraseConstMeta =>
      const TaskConstMeta(
        debugName: "generate_seed_phrase",
        argNames: [],
      );

  @override
  String crateApiSimpleGreet({required String name}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(name, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 40)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiSimpleGreetConstMeta,
      argValues: [name],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSimpleGreetConstMeta => const TaskConstMeta(
        debugName: "greet",
        argNames: ["name"],
      );

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 41, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiSimpleInitAppConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta => const TaskConstMeta(
        debugName: "init_app",
        argNames: [],
      );

  @override
  List<WalletToken> crateApiWalletWalletContextGetAllSupportedTokens() {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 42)!;
      },
      codec: SseCodec(
        decodeSuccessData:
            sse_decode_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWalletToken,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiWalletWalletContextGetAllSupportedTokensConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta
      get kCrateApiWalletWalletContextGetAllSupportedTokensConstMeta =>
          const TaskConstMeta(
            debugName: "wallet_context_get_all_supported_tokens",
            argNames: [],
          );

  @override
  List<WalletToken> crateApiWalletWalletContextGetInitialSupportedTokens() {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 43)!;
      },
      codec: SseCodec(
        decodeSuccessData:
            sse_decode_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWalletToken,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiWalletWalletContextGetInitialSupportedTokensConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta
      get kCrateApiWalletWalletContextGetInitialSupportedTokensConstMeta =>
          const TaskConstMeta(
            debugName: "wallet_context_get_initial_supported_tokens",
            argNames: [],
          );

  @override
  String crateApiWalletWalletContextHashData({required String data}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(data, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 44)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiWalletWalletContextHashDataConstMeta,
      argValues: [data],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiWalletWalletContextHashDataConstMeta =>
      const TaskConstMeta(
        debugName: "wallet_context_hash_data",
        argNames: ["data"],
      );

  @override
  bool crateApiWalletWalletContextVerifyMnemonic({required String mnemonic}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(mnemonic, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 45)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_bool,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiWalletWalletContextVerifyMnemonicConstMeta,
      argValues: [mnemonic],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiWalletWalletContextVerifyMnemonicConstMeta =>
      const TaskConstMeta(
        debugName: "wallet_context_verify_mnemonic",
        argNames: ["mnemonic"],
      );

  @override
  bool crateApiWalletWalletContextVerifyPrincipal({required String text}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(text, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 46)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_bool,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiWalletWalletContextVerifyPrincipalConstMeta,
      argValues: [text],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiWalletWalletContextVerifyPrincipalConstMeta =>
      const TaskConstMeta(
        debugName: "wallet_context_verify_principal",
        argNames: ["text"],
      );

  RustArcIncrementStrongCountFnType
      get rust_arc_increment_strong_count_IcWalletService => wire
          .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerICWalletService;

  RustArcDecrementStrongCountFnType
      get rust_arc_decrement_strong_count_IcWalletService => wire
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerICWalletService;

  RustArcIncrementStrongCountFnType
      get rust_arc_increment_strong_count_TokenMetadata => wire
          .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTokenMetadata;

  RustArcDecrementStrongCountFnType
      get rust_arc_decrement_strong_count_TokenMetadata => wire
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTokenMetadata;

  RustArcIncrementStrongCountFnType
      get rust_arc_increment_strong_count_Wallet => wire
          .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWallet;

  RustArcDecrementStrongCountFnType
      get rust_arc_decrement_strong_count_Wallet => wire
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWallet;

  RustArcIncrementStrongCountFnType
      get rust_arc_increment_strong_count_WalletToken => wire
          .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWalletToken;

  RustArcDecrementStrongCountFnType
      get rust_arc_decrement_strong_count_WalletToken => wire
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWalletToken;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  IcWalletService
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerICWalletService(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return IcWalletServiceImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  TokenMetadata
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTokenMetadata(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return TokenMetadataImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  Wallet
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWallet(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return WalletImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  WalletToken
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWalletToken(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return WalletTokenImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  WalletToken
      dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWalletToken(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return WalletTokenImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  IcWalletService
      dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerICWalletService(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return IcWalletServiceImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  Wallet
      dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWallet(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return WalletImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  WalletToken
      dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWalletToken(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return WalletTokenImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  IcWalletService
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerICWalletService(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return IcWalletServiceImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  TokenMetadata
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTokenMetadata(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return TokenMetadataImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  Wallet
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWallet(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return WalletImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  WalletToken
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWalletToken(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return WalletTokenImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  IWalletService dco_decode_TraitDef_IWalletService(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  BigInt dco_decode_U128(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return BigInt.parse(raw);
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_box_autoadd_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  double dco_decode_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  List<WalletToken>
      dco_decode_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWalletToken(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(
            dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWalletToken)
        .toList();
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<SimpleTransaction> dco_decode_list_simple_transaction(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_simple_transaction).toList();
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_32(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_8(raw);
  }

  @protected
  QuoteResponse dco_decode_quote_response(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return QuoteResponse(
      receiveTokenAddress: dco_decode_String(arr[0]),
      slippage: dco_decode_f_64(arr[1]),
      txCount: dco_decode_usize(arr[2]),
      midPrice: dco_decode_f_64(arr[3]),
      receiveAmount: dco_decode_u_64(arr[4]),
    );
  }

  @protected
  SimpleTransaction dco_decode_simple_transaction(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return SimpleTransaction(
      kind: dco_decode_String(arr[0]),
      amount: dco_decode_String(arr[1]),
      to: dco_decode_String(arr[2]),
      timestamp: dco_decode_u_64(arr[3]),
      symbol: dco_decode_String(arr[4]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  WalletContext dco_decode_wallet_context(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 1)
      throw Exception('unexpected arr length: expect 1 but see ${arr.length}');
    return WalletContext(
      seedPhrase: dco_decode_String(arr[0]),
    );
  }

  @protected
  WalletTokenNetWork dco_decode_wallet_token_net_work(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return WalletTokenNetWork.values[raw as int];
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  IcWalletService
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerICWalletService(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return IcWalletServiceImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  TokenMetadata
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTokenMetadata(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return TokenMetadataImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  Wallet
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWallet(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return WalletImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  WalletToken
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWalletToken(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return WalletTokenImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  WalletToken
      sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWalletToken(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return WalletTokenImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  IcWalletService
      sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerICWalletService(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return IcWalletServiceImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  Wallet
      sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWallet(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return WalletImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  WalletToken
      sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWalletToken(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return WalletTokenImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  IcWalletService
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerICWalletService(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return IcWalletServiceImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  TokenMetadata
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTokenMetadata(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return TokenMetadataImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  Wallet
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWallet(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return WalletImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  WalletToken
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWalletToken(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return WalletTokenImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  BigInt sse_decode_U128(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return BigInt.parse(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_32(deserializer));
  }

  @protected
  int sse_decode_box_autoadd_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_8(deserializer));
  }

  @protected
  double sse_decode_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat32();
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  List<WalletToken>
      sse_decode_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWalletToken(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <WalletToken>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(
          sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWalletToken(
              deserializer));
    }
    return ans_;
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<SimpleTransaction> sse_decode_list_simple_transaction(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <SimpleTransaction>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_simple_transaction(deserializer));
    }
    return ans_;
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_8(deserializer));
    } else {
      return null;
    }
  }

  @protected
  QuoteResponse sse_decode_quote_response(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_receiveTokenAddress = sse_decode_String(deserializer);
    var var_slippage = sse_decode_f_64(deserializer);
    var var_txCount = sse_decode_usize(deserializer);
    var var_midPrice = sse_decode_f_64(deserializer);
    var var_receiveAmount = sse_decode_u_64(deserializer);
    return QuoteResponse(
        receiveTokenAddress: var_receiveTokenAddress,
        slippage: var_slippage,
        txCount: var_txCount,
        midPrice: var_midPrice,
        receiveAmount: var_receiveAmount);
  }

  @protected
  SimpleTransaction sse_decode_simple_transaction(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_kind = sse_decode_String(deserializer);
    var var_amount = sse_decode_String(deserializer);
    var var_to = sse_decode_String(deserializer);
    var var_timestamp = sse_decode_u_64(deserializer);
    var var_symbol = sse_decode_String(deserializer);
    return SimpleTransaction(
        kind: var_kind,
        amount: var_amount,
        to: var_to,
        timestamp: var_timestamp,
        symbol: var_symbol);
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  WalletContext sse_decode_wallet_context(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_seedPhrase = sse_decode_String(deserializer);
    return WalletContext(seedPhrase: var_seedPhrase);
  }

  @protected
  WalletTokenNetWork sse_decode_wallet_token_net_work(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return WalletTokenNetWork.values[inner];
  }

  @protected
  void sse_encode_AnyhowException(
      AnyhowException self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerICWalletService(
          IcWalletService self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as IcWalletServiceImpl).frbInternalSseEncode(move: true),
        serializer);
  }

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTokenMetadata(
          TokenMetadata self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as TokenMetadataImpl).frbInternalSseEncode(move: true),
        serializer);
  }

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWallet(
          Wallet self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as WalletImpl).frbInternalSseEncode(move: true), serializer);
  }

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWalletToken(
          WalletToken self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as WalletTokenImpl).frbInternalSseEncode(move: true), serializer);
  }

  @protected
  void
      sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWalletToken(
          WalletToken self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as WalletTokenImpl).frbInternalSseEncode(move: false),
        serializer);
  }

  @protected
  void
      sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerICWalletService(
          IcWalletService self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as IcWalletServiceImpl).frbInternalSseEncode(move: false),
        serializer);
  }

  @protected
  void
      sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWallet(
          Wallet self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as WalletImpl).frbInternalSseEncode(move: false), serializer);
  }

  @protected
  void
      sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWalletToken(
          WalletToken self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as WalletTokenImpl).frbInternalSseEncode(move: false),
        serializer);
  }

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerICWalletService(
          IcWalletService self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as IcWalletServiceImpl).frbInternalSseEncode(move: null),
        serializer);
  }

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTokenMetadata(
          TokenMetadata self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as TokenMetadataImpl).frbInternalSseEncode(move: null),
        serializer);
  }

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWallet(
          Wallet self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as WalletImpl).frbInternalSseEncode(move: null), serializer);
  }

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWalletToken(
          WalletToken self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as WalletTokenImpl).frbInternalSseEncode(move: null), serializer);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_U128(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.toString(), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_8(self, serializer);
  }

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat32(self);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void
      sse_encode_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWalletToken(
          List<WalletToken> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWalletToken(
          item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
      List<int> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer
        .putUint8List(self is Uint8List ? self : Uint8List.fromList(self));
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_simple_transaction(
      List<SimpleTransaction> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_simple_transaction(item, serializer);
    }
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_32(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_8(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_8(self, serializer);
    }
  }

  @protected
  void sse_encode_quote_response(QuoteResponse self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.receiveTokenAddress, serializer);
    sse_encode_f_64(self.slippage, serializer);
    sse_encode_usize(self.txCount, serializer);
    sse_encode_f_64(self.midPrice, serializer);
    sse_encode_u_64(self.receiveAmount, serializer);
  }

  @protected
  void sse_encode_simple_transaction(
      SimpleTransaction self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.kind, serializer);
    sse_encode_String(self.amount, serializer);
    sse_encode_String(self.to, serializer);
    sse_encode_u_64(self.timestamp, serializer);
    sse_encode_String(self.symbol, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_wallet_context(WalletContext self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.seedPhrase, serializer);
  }

  @protected
  void sse_encode_wallet_token_net_work(
      WalletTokenNetWork self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }
}

@sealed
class IcWalletServiceImpl extends RustOpaque implements IcWalletService {
  // Not to be used by end users
  IcWalletServiceImpl.frbInternalDcoDecode(List<dynamic> wire)
      : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  IcWalletServiceImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
      : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_IcWalletService,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_IcWalletService,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_IcWalletServicePtr,
  );

  /// Approves another account (spender) to spend tokens on behalf of the caller
  Future<BigInt> approve(
          {required WalletToken token,
          required String spender,
          required BigInt amount}) =>
      RustLib.instance.api.crateApiWalletServiceIcWalletServiceApprove(
          that: this, token: token, spender: spender, amount: amount);

  /// Checks if a spender is approved for a certain amount
  Future<BigInt> getAllowance(
          {required WalletToken token,
          required String owner,
          required String spender}) =>
      RustLib.instance.api.crateApiWalletServiceIcWalletServiceGetAllowance(
          that: this, token: token, owner: owner, spender: spender);

  /// Gets the balance of an account for a specific token
  Future<BigInt> getBalance(
          {required WalletToken token, required String account}) =>
      RustLib.instance.api.crateApiWalletServiceIcWalletServiceGetBalance(
          that: this, token: token, account: account);

  Future<List<SimpleTransaction>> getLatestTransactions(
          {required WalletToken token,
          required String accountAddr,
          int? maxResults}) =>
      RustLib.instance.api
          .crateApiWalletServiceIcWalletServiceGetLatestTransactions(
              that: this,
              token: token,
              accountAddr: accountAddr,
              maxResults: maxResults);

  Future<double> getPrice({required WalletToken token}) => RustLib.instance.api
      .crateApiWalletServiceIcWalletServiceGetPrice(that: this, token: token);

  Future<WalletToken> getToken(
          {required String canisterId, String? indexCanister}) =>
      RustLib.instance.api.crateApiWalletServiceIcWalletServiceGetToken(
          that: this, canisterId: canisterId, indexCanister: indexCanister);

  Future<BigInt> send(
          {required WalletToken token,
          required String to,
          required BigInt amount}) =>
      RustLib.instance.api.crateApiWalletServiceIcWalletServiceSend(
          that: this, token: token, to: to, amount: amount);

  Future<QuoteResponse> swapQuote(
          {required WalletToken payToken,
          required WalletToken receiveToken,
          required BigInt payAmount}) =>
      RustLib.instance.api.crateApiWalletServiceIcWalletServiceSwapQuote(
          that: this,
          payToken: payToken,
          receiveToken: receiveToken,
          payAmount: payAmount);
}

@sealed
class TokenMetadataImpl extends RustOpaque implements TokenMetadata {
  // Not to be used by end users
  TokenMetadataImpl.frbInternalDcoDecode(List<dynamic> wire)
      : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  TokenMetadataImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
      : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_TokenMetadata,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_TokenMetadata,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_TokenMetadataPtr,
  );
}

@sealed
class WalletImpl extends RustOpaque implements Wallet {
  // Not to be used by end users
  WalletImpl.frbInternalDcoDecode(List<dynamic> wire)
      : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  WalletImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
      : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_Wallet,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_Wallet,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_WalletPtr,
  );

  Wallet createChildWallet({required String path}) => RustLib.instance.api
      .crateApiWalletWalletCreateChildWallet(that: this, path: path);

  IcWalletService createIcService() =>
      RustLib.instance.api.crateApiWalletWalletCreateIcService(
        that: this,
      );

  Uint8List signMessage({required List<int> message}) => RustLib.instance.api
      .crateApiWalletWalletSignMessage(that: this, message: message);

  String toAccountIdentifier() =>
      RustLib.instance.api.crateApiWalletWalletToAccountIdentifier(
        that: this,
      );

  String toBitcoinAddress() =>
      RustLib.instance.api.crateApiWalletWalletToBitcoinAddress(
        that: this,
      );

  String toIcpPrincipal() =>
      RustLib.instance.api.crateApiWalletWalletToIcpPrincipal(
        that: this,
      );
}

@sealed
class WalletTokenImpl extends RustOpaque implements WalletToken {
  // Not to be used by end users
  WalletTokenImpl.frbInternalDcoDecode(List<dynamic> wire)
      : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  WalletTokenImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
      : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_WalletToken,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_WalletToken,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_WalletTokenPtr,
  );

  String? get govCanister =>
      RustLib.instance.api.crateApiWalletWalletTokenAutoAccessorGetGovCanister(
        that: this,
      );

  String? get imageUrl =>
      RustLib.instance.api.crateApiWalletWalletTokenAutoAccessorGetImageUrl(
        that: this,
      );

  String? get indexCanister => RustLib.instance.api
          .crateApiWalletWalletTokenAutoAccessorGetIndexCanister(
        that: this,
      );

  WalletTokenNetWork get network =>
      RustLib.instance.api.crateApiWalletWalletTokenAutoAccessorGetNetwork(
        that: this,
      );

  String get symbol =>
      RustLib.instance.api.crateApiWalletWalletTokenAutoAccessorGetSymbol(
        that: this,
      );

  String get tokenAddress =>
      RustLib.instance.api.crateApiWalletWalletTokenAutoAccessorGetTokenAddress(
        that: this,
      );

  int? get tokenDecimal =>
      RustLib.instance.api.crateApiWalletWalletTokenAutoAccessorGetTokenDecimal(
        that: this,
      );

  String get tokenName =>
      RustLib.instance.api.crateApiWalletWalletTokenAutoAccessorGetTokenName(
        that: this,
      );

  BigInt get transferFee =>
      RustLib.instance.api.crateApiWalletWalletTokenAutoAccessorGetTransferFee(
        that: this,
      );

  set govCanister(String? govCanister) =>
      RustLib.instance.api.crateApiWalletWalletTokenAutoAccessorSetGovCanister(
          that: this, govCanister: govCanister);

  set imageUrl(String? imageUrl) =>
      RustLib.instance.api.crateApiWalletWalletTokenAutoAccessorSetImageUrl(
          that: this, imageUrl: imageUrl);

  set indexCanister(String? indexCanister) => RustLib.instance.api
      .crateApiWalletWalletTokenAutoAccessorSetIndexCanister(
          that: this, indexCanister: indexCanister);

  set network(WalletTokenNetWork network) =>
      RustLib.instance.api.crateApiWalletWalletTokenAutoAccessorSetNetwork(
          that: this, network: network);

  set symbol(String symbol) =>
      RustLib.instance.api.crateApiWalletWalletTokenAutoAccessorSetSymbol(
          that: this, symbol: symbol);

  set tokenAddress(String tokenAddress) =>
      RustLib.instance.api.crateApiWalletWalletTokenAutoAccessorSetTokenAddress(
          that: this, tokenAddress: tokenAddress);

  set tokenDecimal(int? tokenDecimal) =>
      RustLib.instance.api.crateApiWalletWalletTokenAutoAccessorSetTokenDecimal(
          that: this, tokenDecimal: tokenDecimal);

  set tokenName(String tokenName) =>
      RustLib.instance.api.crateApiWalletWalletTokenAutoAccessorSetTokenName(
          that: this, tokenName: tokenName);

  set transferFee(BigInt transferFee) =>
      RustLib.instance.api.crateApiWalletWalletTokenAutoAccessorSetTransferFee(
          that: this, transferFee: transferFee);

  String toString() => RustLib.instance.api.crateApiWalletWalletTokenToString(
        that: this,
      );
}
