[package]
name = "fusion_pay"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
candid = { workspace = true }
ic-cdk = { workspace = true }
ic-cdk-timers = { workspace = true }
serde = { workspace = true }
ic-stable-structures = { workspace = true }
hex = { workspace = true }
ic-http-certification = { workspace = true }
lazy_static = { workspace = true }
include_dir = { workspace = true }
serde_json = { workspace = true }
handlebars = { workspace = true }
ciborium = { workspace = true }