// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.7.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `format_amount`, `from_metadata_records`, `new`, `to_hex`
// These types are ignored because they are not used by any `pub` functions: `AccountIdentifier`, `Subaccount`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `_ty`, `_ty`, `_ty`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `clone`, `clone`, `cmp`, `cmp`, `eq`, `eq`, `fmt`, `fmt`, `from`, `hash`, `hash`, `id`, `id`, `id`, `idl_serialize`, `idl_serialize`, `idl_serialize`, `partial_cmp`, `partial_cmp`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<TokenMetadata>>
abstract class TokenMetadata implements RustOpaqueInterface {
  static Future<TokenMetadata> default_() =>
      RustLib.instance.api.crateApiUtilsTokenMetadataDefault();
}
