// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.7.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'wallet_service.dart';

// These functions are ignored because they are not marked as `pub`: `ascii_to_hardened_derivation_path`, `from_private_key`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`

Future<String> generateSeedPhrase() =>
    RustLib.instance.api.crateApiWalletGenerateSeedPhrase();

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Wallet>>
abstract class Wallet implements RustOpaqueInterface, IWalletService {
  @override
  Wallet createChildWallet({required String path});

  IcWalletService createIcService();

  static Wallet fromSeed({required String seedPhrase}) =>
      RustLib.instance.api.crateApiWalletWalletFromSeed(seedPhrase: seedPhrase);

  @override
  Uint8List signMessage({required List<int> message});

  String toAccountIdentifier();

  String toBitcoinAddress();

  String toIcpPrincipal();
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<WalletToken>>
abstract class WalletToken implements RustOpaqueInterface {
  String? get govCanister;

  String? get imageUrl;

  String? get indexCanister;

  WalletTokenNetWork get network;

  String get symbol;

  String get tokenAddress;

  int? get tokenDecimal;

  String get tokenName;

  BigInt get transferFee;

  set govCanister(String? govCanister);

  set imageUrl(String? imageUrl);

  set indexCanister(String? indexCanister);

  set network(WalletTokenNetWork network);

  set symbol(String symbol);

  set tokenAddress(String tokenAddress);

  set tokenDecimal(int? tokenDecimal);

  set tokenName(String tokenName);

  set transferFee(BigInt transferFee);
}

abstract class IWalletService {
  Wallet createChildWallet({required String path});

  Uint8List signMessage({required List<int> message});
}

class WalletContext {
  final String seedPhrase;

  const WalletContext({
    required this.seedPhrase,
  });

  static Future<List<WalletToken>> getAllSupportedTokens() =>
      RustLib.instance.api.crateApiWalletWalletContextGetAllSupportedTokens();

  static List<WalletToken> getInitialSupportedTokens() => RustLib.instance.api
      .crateApiWalletWalletContextGetInitialSupportedTokens();

  static String hashData({required String data}) =>
      RustLib.instance.api.crateApiWalletWalletContextHashData(data: data);

  static bool verifyMnemonic({required String mnemonic}) => RustLib.instance.api
      .crateApiWalletWalletContextVerifyMnemonic(mnemonic: mnemonic);

  static bool verifyPrincipal({required String text}) => RustLib.instance.api
      .crateApiWalletWalletContextVerifyPrincipal(text: text);

  @override
  int get hashCode => seedPhrase.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WalletContext &&
          runtimeType == other.runtimeType &&
          seedPhrase == other.seedPhrase;
}

enum WalletTokenNetWork {
  bitcoin,
  internetComputer,
  ;
}
