/*
 * Fusion Wallet - A non-custodial cryptocurrency wallet
 * Copyright (C) 2025 Fusion Wallet
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 */


// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'canister.freezed.dart';
part 'canister.g.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `fmt`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `new`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ICCanisterInfoService>>
abstract class IcCanisterInfoService implements RustOpaqueInterface {
  Future<CanisterMetric> getCanisterStatus({required String canisterId});
}

@freezed
class CanisterMetric with _$CanisterMetric {
  const factory CanisterMetric({
    required BigInt memorySize,
    required BigInt cyclesBalance,
    required String status,
    required String canisterId,
    required BigInt totalCalls,
    required BigInt totalOutboundBytes,
    required BigInt totalInboundBytes,
  }) = _CanisterMetric;

  factory CanisterMetric.fromJson(Map<String, dynamic> json) =>
      _$CanisterMetricFromJson(json);
}
