/*
 * Fusion Wallet - A non-custodial cryptocurrency wallet
 * Copyright (C) 2025 Fusion Wallet
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 */


// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../lib.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `create_canister`, `get_build_metadata`, `get_default_subnets`, `get_principals_authorized_to_create_canisters_to_subnets`, `get_subnet_types_to_subnets`, `notify_create_canister`, `notify_top_up`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `CanisterSettings`, `CreateCanisterArg`, `CreateCanisterError`, `CreateCanisterResult`, `ExchangeRateCanister`, `LogVisibility`, `NotifyCreateCanisterArg`, `NotifyCreateCanisterResult`, `NotifyError`, `NotifyMintCyclesArg`, `NotifyMintCyclesResult`, `NotifyMintCyclesSuccess`, `NotifyTopUpArg`, `NotifyTopUpResult`, `PrincipalsAuthorizedToCreateCanistersToSubnetsResponse`, `RejectionCode`, `SubnetFilter`, `SubnetSelection`, `SubnetTypesToSubnetsResponse`, `WithdrawArgs`, `WithdrawError`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `_ty`, `_ty`, `_ty`, `_ty`, `_ty`, `_ty`, `_ty`, `_ty`, `_ty`, `_ty`, `_ty`, `_ty`, `_ty`, `_ty`, `_ty`, `_ty`, `_ty`, `_ty`, `_ty`, `_ty`, `_ty`, `_ty`, `_ty`, `fmt`, `fmt`, `fmt`, `id`, `id`, `id`, `id`, `id`, `id`, `id`, `id`, `id`, `id`, `id`, `id`, `id`, `id`, `id`, `id`, `id`, `id`, `id`, `id`, `id`, `id`, `id`, `idl_serialize`, `idl_serialize`, `idl_serialize`, `idl_serialize`, `idl_serialize`, `idl_serialize`, `idl_serialize`, `idl_serialize`, `idl_serialize`, `idl_serialize`, `idl_serialize`, `idl_serialize`, `idl_serialize`, `idl_serialize`, `idl_serialize`, `idl_serialize`, `idl_serialize`, `idl_serialize`, `idl_serialize`, `idl_serialize`, `idl_serialize`, `idl_serialize`, `idl_serialize`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `new`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<CyclesService>>
abstract class CyclesService implements RustOpaqueInterface {
  Future<IcpXdrConversionRateResponse> getIcpXdrConversionRate();

  Future<MintSuccess> notifyMintCycles(
      {required BigInt blockIndex,
      BigInt? depositMemo,
      U8Array32? toSubaccount});

  Future<BigInt> withdraw(
      {required String to, required BigInt amount, Uint8List? fromSubaccount});
}

class IcpXdrConversionRate {
  final BigInt xdrPermyriadPerIcp;
  final BigInt timestampSeconds;

  const IcpXdrConversionRate({
    required this.xdrPermyriadPerIcp,
    required this.timestampSeconds,
  });

  @override
  int get hashCode => xdrPermyriadPerIcp.hashCode ^ timestampSeconds.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is IcpXdrConversionRate &&
          runtimeType == other.runtimeType &&
          xdrPermyriadPerIcp == other.xdrPermyriadPerIcp &&
          timestampSeconds == other.timestampSeconds;
}

class IcpXdrConversionRateResponse {
  final Uint8List certificate;
  final IcpXdrConversionRate data;
  final Uint8List hashTree;

  const IcpXdrConversionRateResponse({
    required this.certificate,
    required this.data,
    required this.hashTree,
  });

  @override
  int get hashCode => certificate.hashCode ^ data.hashCode ^ hashTree.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is IcpXdrConversionRateResponse &&
          runtimeType == other.runtimeType &&
          certificate == other.certificate &&
          data == other.data &&
          hashTree == other.hashTree;
}

class MintSuccess {
  final BigInt balance;
  final BigInt blockIndex;
  final BigInt minted;

  const MintSuccess({
    required this.balance,
    required this.blockIndex,
    required this.minted,
  });

  @override
  int get hashCode => balance.hashCode ^ blockIndex.hashCode ^ minted.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MintSuccess &&
          runtimeType == other.runtimeType &&
          balance == other.balance &&
          blockIndex == other.blockIndex &&
          minted == other.minted;
}
