// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'wallet.dart';

// These functions are ignored because they are not marked as `pub`: `new`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `fmt`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<HttpWalletService>>
abstract class HttpWalletService implements RustOpaqueInterface {
  Future<GithubRelease> getLatestRelease();

  Future<double?> getPrice({required WalletToken token});
}

class GithubRelease {
  final String tagName;
  final String htmlUrl;
  final String? body;

  const GithubRelease({
    required this.tagName,
    required this.htmlUrl,
    this.body,
  });

  @override
  int get hashCode => tagName.hashCode ^ htmlUrl.hashCode ^ body.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GithubRelease &&
          runtimeType == other.runtimeType &&
          tagName == other.tagName &&
          htmlUrl == other.htmlUrl &&
          body == other.body;
}
