/*
 * Fusion Wallet - A non-custodial cryptocurrency wallet
 * Copyright (C) 2025 Fusion Wallet
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 */


// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'canister.dart';
import 'cmc.dart';
import 'nft_service.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'wallet.dart';

// These functions are ignored because they are not marked as `pub`: `create_index_service`, `new`, `verify_index`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ICWalletService>>
abstract class IcWalletService implements RustOpaqueInterface {
  /// Approves another account (spender) to spend tokens on behalf of the caller
  Future<BigInt> approve(
      {required WalletToken token,
      required String spender,
      required BigInt amount,
      BigInt? expiresAt});

  IcCanisterInfoService createCanisterInfoService();

  IcCollectionService createCollectionService();

  CyclesService createCyclesService();

  /// Checks if a spender is approved for a certain amount
  Future<AllowanceResponse> getAllowance(
      {required WalletToken token,
      required String owner,
      required String spender});

  /// Gets the balance of an account for a specific token
  Future<BigInt> getBalance(
      {required WalletToken token, required String account});

  Future<List<SimpleTransaction>> getLatestTransactions(
      {required WalletToken token,
      required String accountAddr,
      int? maxResults});

  Future<WalletToken> getToken(
      {required String canisterId, String? indexCanister});

  Future<BigInt> icpAccountIdSend(
      {required String to, required BigInt amount, BigInt? memo});

  Future<BigInt> send(
      {required WalletToken token, required String to, required BigInt amount});

  Future<SwapResponse> swap(
      {required WalletToken payToken,
      required WalletToken receiveToken,
      required BigInt payAmount,
      double? slippage});

  Future<QuoteResponse> swapQuote(
      {required WalletToken payToken,
      required WalletToken receiveToken,
      required BigInt payAmount});
}

class AllowanceResponse {
  final BigInt allowance;
  final BigInt? expiresAt;

  const AllowanceResponse({
    required this.allowance,
    this.expiresAt,
  });

  @override
  int get hashCode => allowance.hashCode ^ expiresAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AllowanceResponse &&
          runtimeType == other.runtimeType &&
          allowance == other.allowance &&
          expiresAt == other.expiresAt;
}

class QuoteResponse {
  final String receiveTokenAddress;
  final double slippage;
  final BigInt txCount;
  final double midPrice;
  final BigInt receiveAmount;
  final BigInt estimatedFeeAmount;

  const QuoteResponse({
    required this.receiveTokenAddress,
    required this.slippage,
    required this.txCount,
    required this.midPrice,
    required this.receiveAmount,
    required this.estimatedFeeAmount,
  });

  @override
  int get hashCode =>
      receiveTokenAddress.hashCode ^
      slippage.hashCode ^
      txCount.hashCode ^
      midPrice.hashCode ^
      receiveAmount.hashCode ^
      estimatedFeeAmount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is QuoteResponse &&
          runtimeType == other.runtimeType &&
          receiveTokenAddress == other.receiveTokenAddress &&
          slippage == other.slippage &&
          txCount == other.txCount &&
          midPrice == other.midPrice &&
          receiveAmount == other.receiveAmount &&
          estimatedFeeAmount == other.estimatedFeeAmount;
}

class SimpleTransaction {
  final String kind;
  final String amount;
  final String to;
  final BigInt timestamp;
  final String symbol;

  const SimpleTransaction({
    required this.kind,
    required this.amount,
    required this.to,
    required this.timestamp,
    required this.symbol,
  });

  @override
  int get hashCode =>
      kind.hashCode ^
      amount.hashCode ^
      to.hashCode ^
      timestamp.hashCode ^
      symbol.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SimpleTransaction &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          amount == other.amount &&
          to == other.to &&
          timestamp == other.timestamp &&
          symbol == other.symbol;
}

class SwapResponse {
  final BigInt txId;
  final String status;
  final String paySymbol;
  final String receiveSymbol;
  final BigInt payAmount;
  final BigInt receiveAmount;

  const SwapResponse({
    required this.txId,
    required this.status,
    required this.paySymbol,
    required this.receiveSymbol,
    required this.payAmount,
    required this.receiveAmount,
  });

  @override
  int get hashCode =>
      txId.hashCode ^
      status.hashCode ^
      paySymbol.hashCode ^
      receiveSymbol.hashCode ^
      payAmount.hashCode ^
      receiveAmount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SwapResponse &&
          runtimeType == other.runtimeType &&
          txId == other.txId &&
          status == other.status &&
          paySymbol == other.paySymbol &&
          receiveSymbol == other.receiveSymbol &&
          payAmount == other.payAmount &&
          receiveAmount == other.receiveAmount;
}
