/*
 * Fusion Wallet - A non-custodial cryptocurrency wallet
 * Copyright (C) 2025 Fusion Wallet
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 */


// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.7.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../lib.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `convert_to_simple_transaction`, `get_account_transactions`, `new`
// These types are ignored because they are not used by any `pub` functions: `GetAccountIdentifierTransactionsArgs`, `GetAccountIdentifierTransactionsError`, `GetAccountIdentifierTransactionsResponse`, `ICPLedgerIndexService`, `ICPTransactionWithId`, `ICPTransaction`, `Operation`, `TimeStamp`, `Tokens`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `_ty`, `_ty`, `_ty`, `_ty`, `_ty`, `_ty`, `_ty`, `_ty`, `_ty`, `id`, `id`, `id`, `id`, `id`, `id`, `id`, `id`, `id`, `idl_serialize`, `idl_serialize`, `idl_serialize`, `idl_serialize`, `idl_serialize`, `idl_serialize`, `idl_serialize`, `idl_serialize`, `idl_serialize`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ICPGetAccountTransactionsArgs>>
abstract class IcpGetAccountTransactionsArgs implements RustOpaqueInterface {
  Account get account;

  Nat get maxResults;

  Nat? get start;

  set account(Account account);

  set maxResults(Nat maxResults);

  set start(Nat? start);
}
