/*
 * Fusion Wallet - A non-custodial cryptocurrency wallet
 * Copyright (C) 2025 Fusion Wallet
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 */


// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.7.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'nft_service.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `from_metadata_records`, `new`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `from`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ICCollectionService>>
abstract class IcCollectionService implements RustOpaqueInterface {
  Future<WalletCollection> getCollection({required String tokenAddrress});

  Future<int> getOwnedCollectibleCount(
      {required WalletCollection collection, required String account});

  Future<List<(BigInt, Map<String, CollectMetaValue>)>> getTokensOwnedByAccount(
      {required WalletCollection collection, required String account});

  Future<BigInt> transferToken(
      {required WalletCollection collection,
      required BigInt tokenId,
      required String to});
}

@freezed
sealed class CollectMetaValue with _$CollectMetaValue {
  const CollectMetaValue._();

  const factory CollectMetaValue.text(
    String field0,
  ) = CollectMetaValue_Text;
  const factory CollectMetaValue.int(
    PlatformInt64 field0,
  ) = CollectMetaValue_Int;
  const factory CollectMetaValue.nat(
    BigInt field0,
  ) = CollectMetaValue_Nat;
  const factory CollectMetaValue.blob(
    Uint8List field0,
  ) = CollectMetaValue_Blob;
}

class WalletCollection {
  final String tokenAddress;
  final String name;
  final String? desciption;
  final String? imageUrl;
  final String symbol;

  const WalletCollection({
    required this.tokenAddress,
    required this.name,
    this.desciption,
    this.imageUrl,
    required this.symbol,
  });

  static Future<WalletCollection> default_() =>
      RustLib.instance.api.crateApiNftServiceWalletCollectionDefault();

  static WalletCollection fromString({required String data}) =>
      RustLib.instance.api
          .crateApiNftServiceWalletCollectionFromString(data: data);

  @override
  String toString() =>
      RustLib.instance.api.crateApiNftServiceWalletCollectionToString(
        that: this,
      );

  @override
  int get hashCode =>
      tokenAddress.hashCode ^
      name.hashCode ^
      desciption.hashCode ^
      imageUrl.hashCode ^
      symbol.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WalletCollection &&
          runtimeType == other.runtimeType &&
          tokenAddress == other.tokenAddress &&
          name == other.name &&
          desciption == other.desciption &&
          imageUrl == other.imageUrl &&
          symbol == other.symbol;
}
