// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `CanisterPermissionInfo`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `_ty`, `_ty`, `clone`, `clone`, `fmt`, `fmt`, `id`, `id`, `idl_serialize`, `idl_serialize`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `new`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<NotificationService>>
abstract class NotificationService implements RustOpaqueInterface {
  Future<void> addAppPermission(
      {required String appId, String? domain, String? name, String? iconUrl});

  Future<void> addDeviceToken({required String token});

  Future<List<CanisterPermission>> getCanisterPermissions();

  Future<void> removeAppPermission({required String appId});

  Future<void> removeDeviceToken({required String token});

  Future<void> sendTransferMessage(
      {required String ledgerCanisterId, required BigInt blockHeight});

  Future<void> updateAppPermission(
      {required String appId, required bool permission});
}

class AppInfo {
  final String? domain;
  final String? name;
  final String? iconUrl;
  final String canisterId;

  const AppInfo({
    this.domain,
    this.name,
    this.iconUrl,
    required this.canisterId,
  });

  @override
  int get hashCode =>
      domain.hashCode ^ name.hashCode ^ iconUrl.hashCode ^ canisterId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AppInfo &&
          runtimeType == other.runtimeType &&
          domain == other.domain &&
          name == other.name &&
          iconUrl == other.iconUrl &&
          canisterId == other.canisterId;
}

class CanisterPermission {
  final String canisterId;
  bool enabled;
  final AppInfo appInfo;

  CanisterPermission({
    required this.canisterId,
    required this.enabled,
    required this.appInfo,
  });

  @override
  int get hashCode => canisterId.hashCode ^ enabled.hashCode ^ appInfo.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CanisterPermission &&
          runtimeType == other.runtimeType &&
          canisterId == other.canisterId &&
          enabled == other.enabled &&
          appInfo == other.appInfo;
}
