/*
 * Fusion Wallet - A non-custodial cryptocurrency wallet
 * Copyright (C) 2025 Fusion Wallet
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 */


// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.7.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../lib.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `get_pools`, `get_swap_amounts`, `get_tokens`, `get_user_balances`, `new`, `swap`
// These types are ignored because they are not used by any `pub` functions: `IcTokenReply`, `IcTransferReply`, `KongSwapService`, `LpBalancesReply`, `LpTokenReply`, `PoolReply`, `PoolsReply`, `SwapAmountsReply`, `SwapAmountsTxReply`, `SwapArgs`, `TokenReply`, `TransferReply`, `TxId`, `UserBalancesReply`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `_ty`, `_ty`, `_ty`, `_ty`, `_ty`, `_ty`, `_ty`, `_ty`, `_ty`, `_ty`, `_ty`, `_ty`, `_ty`, `_ty`, `_ty`, `_ty`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `id`, `id`, `id`, `id`, `id`, `id`, `id`, `id`, `id`, `id`, `id`, `id`, `id`, `id`, `id`, `id`, `idl_serialize`, `idl_serialize`, `idl_serialize`, `idl_serialize`, `idl_serialize`, `idl_serialize`, `idl_serialize`, `idl_serialize`, `idl_serialize`, `idl_serialize`, `idl_serialize`, `idl_serialize`, `idl_serialize`, `idl_serialize`, `idl_serialize`, `idl_serialize`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<SwapReply>>
abstract class SwapReply implements RustOpaqueInterface {
  Uint64List get claimIds;

  double get midPrice;

  String get payAddress;

  Nat get payAmount;

  String get payChain;

  String get paySymbol;

  double get price;

  String get receiveAddress;

  Nat get receiveAmount;

  String get receiveChain;

  String get receiveSymbol;

  BigInt get requestId;

  double get slippage;

  String get status;

  List<TransferIdReply> get transferIds;

  BigInt get ts;

  BigInt get txId;

  List<SwapTxReply> get txs;

  set claimIds(Uint64List claimIds);

  set midPrice(double midPrice);

  set payAddress(String payAddress);

  set payAmount(Nat payAmount);

  set payChain(String payChain);

  set paySymbol(String paySymbol);

  set price(double price);

  set receiveAddress(String receiveAddress);

  set receiveAmount(Nat receiveAmount);

  set receiveChain(String receiveChain);

  set receiveSymbol(String receiveSymbol);

  set requestId(BigInt requestId);

  set slippage(double slippage);

  set status(String status);

  set transferIds(List<TransferIdReply> transferIds);

  set ts(BigInt ts);

  set txId(BigInt txId);

  set txs(List<SwapTxReply> txs);
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<SwapTxReply>>
abstract class SwapTxReply implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<TransferIdReply>>
abstract class TransferIdReply implements RustOpaqueInterface {}
