// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.7.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../lib.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'swap_service.freezed.dart';

            // These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `_ty`, `_ty`, `_ty`, `_ty`, `_ty`, `_ty`, `_ty`, `_ty`, `_ty`, `_ty`, `_ty`, `_ty`, `_ty`, `_ty`, `_ty`, `_ty`, `clone`, `clone`, `id`, `id`, `id`, `id`, `id`, `id`, `id`, `id`, `id`, `id`, `id`, `id`, `id`, `id`, `id`, `id`, `idl_serialize`, `idl_serialize`, `idl_serialize`, `idl_serialize`, `idl_serialize`, `idl_serialize`, `idl_serialize`, `idl_serialize`, `idl_serialize`, `idl_serialize`, `idl_serialize`, `idl_serialize`, `idl_serialize`, `idl_serialize`, `idl_serialize`, `idl_serialize`


            

            
                // Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Agent>>
                abstract class Agent implements RustOpaqueInterface {
                    

                    
                }
                


                // Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ICSwapService>>
                abstract class IcSwapService implements RustOpaqueInterface {
                     Future<PoolsReply>  getPools({String? filterToken });


 Future<SwapAmountsReply>  getSwapAmounts({required String payToken , required Nat payAmount , required String receiveToken });


 Future<List<TokenReply>>  getTokens({String? filterSymbol });


 Future<List<UserBalancesReply>>  getUserBalances({required String principalId });


  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
static Future<IcSwapService>  newInstance({required Agent icAgent , required Principal swapCanisterId })=>RustLib.instance.api.crateApiSwapServiceIcSwapServiceNew(icAgent: icAgent, swapCanisterId: swapCanisterId);


 Future<SwapReply>  swap({required SwapArgs args });



                    
                }
                


                // Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<IcTokenReply>>
                abstract class IcTokenReply implements RustOpaqueInterface {
                     String get canisterId;


 String get chain;


 int get decimals;


 Nat get fee;


 bool get icrc1;


 bool get icrc2;


 bool get icrc3;


 bool get isRemoved;


 String get name;


 String get symbol;


 int get tokenId;


  set canisterId(String canisterId);


  set chain(String chain);


  set decimals(int decimals);


  set fee(Nat fee);


  set icrc1(bool icrc1);


  set icrc2(bool icrc2);


  set icrc3(bool icrc3);


  set isRemoved(bool isRemoved);


  set name(String name);


  set symbol(String symbol);


  set tokenId(int tokenId);



                    
                }
                


                // Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<IcTransferReply>>
                abstract class IcTransferReply implements RustOpaqueInterface {
                     Nat get amount;


 Nat get blockIndex;


 String get canisterId;


 String get chain;


 bool get isSend;


 String get symbol;


  set amount(Nat amount);


  set blockIndex(Nat blockIndex);


  set canisterId(String canisterId);


  set chain(String chain);


  set isSend(bool isSend);


  set symbol(String symbol);



                    
                }
                


                // Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<LpTokenReply>>
                abstract class LpTokenReply implements RustOpaqueInterface {
                     String get address;


 String get chain;


 int get decimals;


 Nat get fee;


 bool get isRemoved;


 String get name;


 int get poolIdOf;


 String get symbol;


 int get tokenId;


 Nat get totalSupply;


  set address(String address);


  set chain(String chain);


  set decimals(int decimals);


  set fee(Nat fee);


  set isRemoved(bool isRemoved);


  set name(String name);


  set poolIdOf(int poolIdOf);


  set symbol(String symbol);


  set tokenId(int tokenId);


  set totalSupply(Nat totalSupply);



                    
                }
                


                // Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<PoolReply>>
                abstract class PoolReply implements RustOpaqueInterface {
                     String get address0;


 String get address1;


 Nat get balance0;


 Nat get balance1;


 String get chain0;


 String get chain1;


 bool get isRemoved;


 Nat get lpFee0;


 Nat get lpFee1;


 int get lpFeeBps;


 String get lpTokenSymbol;


 String get name;


 int get poolId;


 double get price;


 double get rolling24HApy;


 Nat get rolling24HLpFee;


 Nat get rolling24HNumSwaps;


 Nat get rolling24HVolume;


 String get symbol;


 String get symbol0;


 String get symbol1;


 Nat get tvl;


  set address0(String address0);


  set address1(String address1);


  set balance0(Nat balance0);


  set balance1(Nat balance1);


  set chain0(String chain0);


  set chain1(String chain1);


  set isRemoved(bool isRemoved);


  set lpFee0(Nat lpFee0);


  set lpFee1(Nat lpFee1);


  set lpFeeBps(int lpFeeBps);


  set lpTokenSymbol(String lpTokenSymbol);


  set name(String name);


  set poolId(int poolId);


  set price(double price);


  set rolling24HApy(double rolling24HApy);


  set rolling24HLpFee(Nat rolling24HLpFee);


  set rolling24HNumSwaps(Nat rolling24HNumSwaps);


  set rolling24HVolume(Nat rolling24HVolume);


  set symbol(String symbol);


  set symbol0(String symbol0);


  set symbol1(String symbol1);


  set tvl(Nat tvl);



                    
                }
                


                // Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<PoolsReply>>
                abstract class PoolsReply implements RustOpaqueInterface {
                     List<PoolReply> get pools;


 Nat get total24HLpFee;


 Nat get total24HNumSwaps;


 Nat get total24HVolume;


 Nat get totalTvl;


  set pools(List<PoolReply> pools);


  set total24HLpFee(Nat total24HLpFee);


  set total24HNumSwaps(Nat total24HNumSwaps);


  set total24HVolume(Nat total24HVolume);


  set totalTvl(Nat totalTvl);



                    
                }
                


                // Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Principal>>
                abstract class Principal implements RustOpaqueInterface {
                    

                    
                }
                


                // Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<SwapAmountsReply>>
                abstract class SwapAmountsReply implements RustOpaqueInterface {
                     double get midPrice;


 String get payAddress;


 Nat get payAmount;


 String get payChain;


 String get paySymbol;


 double get price;


 String get receiveAddress;


 Nat get receiveAmount;


 String get receiveChain;


 String get receiveSymbol;


 double get slippage;


 List<SwapAmountsTxReply> get txs;


  set midPrice(double midPrice);


  set payAddress(String payAddress);


  set payAmount(Nat payAmount);


  set payChain(String payChain);


  set paySymbol(String paySymbol);


  set price(double price);


  set receiveAddress(String receiveAddress);


  set receiveAmount(Nat receiveAmount);


  set receiveChain(String receiveChain);


  set receiveSymbol(String receiveSymbol);


  set slippage(double slippage);


  set txs(List<SwapAmountsTxReply> txs);



                    
                }
                


                // Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<SwapAmountsTxReply>>
                abstract class SwapAmountsTxReply implements RustOpaqueInterface {
                     Nat get gasFee;


 Nat get lpFee;


 String get payAddress;


 Nat get payAmount;


 String get payChain;


 String get paySymbol;


 String get poolSymbol;


 double get price;


 String get receiveAddress;


 Nat get receiveAmount;


 String get receiveChain;


 String get receiveSymbol;


  set gasFee(Nat gasFee);


  set lpFee(Nat lpFee);


  set payAddress(String payAddress);


  set payAmount(Nat payAmount);


  set payChain(String payChain);


  set paySymbol(String paySymbol);


  set poolSymbol(String poolSymbol);


  set price(double price);


  set receiveAddress(String receiveAddress);


  set receiveAmount(Nat receiveAmount);


  set receiveChain(String receiveChain);


  set receiveSymbol(String receiveSymbol);



                    
                }
                


                // Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<SwapArgs>>
                abstract class SwapArgs implements RustOpaqueInterface {
                     double? get maxSlippage;


 Nat get payAmount;


 String get payToken;


 TxId? get payTxId;


 String? get receiveAddress;


 Nat? get receiveAmount;


 String get receiveToken;


 String? get referredBy;


  set maxSlippage(double? maxSlippage);


  set payAmount(Nat payAmount);


  set payToken(String payToken);


  set payTxId(TxId? payTxId);


  set receiveAddress(String? receiveAddress);


  set receiveAmount(Nat? receiveAmount);


  set receiveToken(String receiveToken);


  set referredBy(String? referredBy);



                    
                }
                


                // Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<SwapReply>>
                abstract class SwapReply implements RustOpaqueInterface {
                     Uint64List get claimIds;


 double get midPrice;


 String get payAddress;


 Nat get payAmount;


 String get payChain;


 String get paySymbol;


 double get price;


 String get receiveAddress;


 Nat get receiveAmount;


 String get receiveChain;


 String get receiveSymbol;


 BigInt get requestId;


 double get slippage;


 String get status;


 List<TransferIdReply> get transferIds;


 BigInt get ts;


 BigInt get txId;


 List<SwapTxReply> get txs;


  set claimIds(Uint64List claimIds);


  set midPrice(double midPrice);


  set payAddress(String payAddress);


  set payAmount(Nat payAmount);


  set payChain(String payChain);


  set paySymbol(String paySymbol);


  set price(double price);


  set receiveAddress(String receiveAddress);


  set receiveAmount(Nat receiveAmount);


  set receiveChain(String receiveChain);


  set receiveSymbol(String receiveSymbol);


  set requestId(BigInt requestId);


  set slippage(double slippage);


  set status(String status);


  set transferIds(List<TransferIdReply> transferIds);


  set ts(BigInt ts);


  set txId(BigInt txId);


  set txs(List<SwapTxReply> txs);



                    
                }
                


                // Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<SwapTxReply>>
                abstract class SwapTxReply implements RustOpaqueInterface {
                     Nat get gasFee;


 Nat get lpFee;


 String get payAddress;


 Nat get payAmount;


 String get payChain;


 String get paySymbol;


 String get poolSymbol;


 double get price;


 String get receiveAddress;


 Nat get receiveAmount;


 String get receiveChain;


 String get receiveSymbol;


 BigInt get ts;


  set gasFee(Nat gasFee);


  set lpFee(Nat lpFee);


  set payAddress(String payAddress);


  set payAmount(Nat payAmount);


  set payChain(String payChain);


  set paySymbol(String paySymbol);


  set poolSymbol(String poolSymbol);


  set price(double price);


  set receiveAddress(String receiveAddress);


  set receiveAmount(Nat receiveAmount);


  set receiveChain(String receiveChain);


  set receiveSymbol(String receiveSymbol);


  set ts(BigInt ts);



                    
                }
                


                // Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<TokenReply>>
                abstract class TokenReply implements RustOpaqueInterface {
                    

                    
                }
                


                // Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<TransferIdReply>>
                abstract class TransferIdReply implements RustOpaqueInterface {
                     TransferReply get transfer;


 BigInt get transferId;


  set transfer(TransferReply transfer);


  set transferId(BigInt transferId);



                    
                }
                


                // Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<TransferReply>>
                abstract class TransferReply implements RustOpaqueInterface {
                    

                    
                }
                


                // Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<TxId>>
                abstract class TxId implements RustOpaqueInterface {
                    

                    
                }
                

class LpBalancesReply  {
                final BigInt ts;
final double usdBalance;
final double balance;
final String name;
final double amount0;
final double amount1;
final String address0;
final String address1;
final String symbol0;
final String symbol1;
final double usdAmount0;
final double usdAmount1;
final String chain0;
final String chain1;
final String symbol;

                const LpBalancesReply({required this.ts ,required this.usdBalance ,required this.balance ,required this.name ,required this.amount0 ,required this.amount1 ,required this.address0 ,required this.address1 ,required this.symbol0 ,required this.symbol1 ,required this.usdAmount0 ,required this.usdAmount1 ,required this.chain0 ,required this.chain1 ,required this.symbol ,});

                
                

                
        @override
        int get hashCode => ts.hashCode^usdBalance.hashCode^balance.hashCode^name.hashCode^amount0.hashCode^amount1.hashCode^address0.hashCode^address1.hashCode^symbol0.hashCode^symbol1.hashCode^usdAmount0.hashCode^usdAmount1.hashCode^chain0.hashCode^chain1.hashCode^symbol.hashCode;
        

                
        @override
        bool operator ==(Object other) =>
            identical(this, other) ||
            other is LpBalancesReply &&
                runtimeType == other.runtimeType
                && ts == other.ts&& usdBalance == other.usdBalance&& balance == other.balance&& name == other.name&& amount0 == other.amount0&& amount1 == other.amount1&& address0 == other.address0&& address1 == other.address1&& symbol0 == other.symbol0&& symbol1 == other.symbol1&& usdAmount0 == other.usdAmount0&& usdAmount1 == other.usdAmount1&& chain0 == other.chain0&& chain1 == other.chain1&& symbol == other.symbol;
        
            }

@freezed
                sealed class UserBalancesReply with _$UserBalancesReply  {
                    const UserBalancesReply._();

                     const factory UserBalancesReply.lp(  LpBalancesReply field0,) = UserBalancesReply_Lp;

                    
                }
            