/*
 * Fusion Wallet - A non-custodial cryptocurrency wallet
 * Copyright (C) 2025 Fusion Wallet
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 */


// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.7.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'http_service.dart';
import 'ic_wallet_service.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `ascii_to_hardened_derivation_path`, `from_private_key`
// These types are ignored because they are not used by any `pub` functions: `CLIENT`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `deref`, `initialize`

Future<String> generateSeedPhrase() =>
    RustLib.instance.api.crateApiWalletGenerateSeedPhrase();

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Wallet>>
abstract class Wallet implements RustOpaqueInterface, IWalletService {
  @override
  Wallet createChildWallet({required String path});

  IcWalletService createIcService();

  static Wallet fromSeed({required String seedPhrase}) =>
      RustLib.instance.api.crateApiWalletWalletFromSeed(seedPhrase: seedPhrase);

  @override
  Uint8List signMessage({required List<int> message});

  String toAccountIdentifier();

  String toIcpPrincipal();
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<WalletToken>>
abstract class WalletToken implements RustOpaqueInterface {
  String? get govCanister;

  String? get imageUrl;

  String? get indexCanister;

  WalletTokenNetWork get network;

  String get symbol;

  String get tokenAddress;

  int? get tokenDecimal;

  String get tokenName;

  BigInt get transferFee;

  set govCanister(String? govCanister);

  set imageUrl(String? imageUrl);

  set indexCanister(String? indexCanister);

  set network(WalletTokenNetWork network);

  set symbol(String symbol);

  set tokenAddress(String tokenAddress);

  set tokenDecimal(int? tokenDecimal);

  set tokenName(String tokenName);

  set transferFee(BigInt transferFee);

  static WalletToken fromString({required String data}) =>
      RustLib.instance.api.crateApiWalletWalletTokenFromString(data: data);

  @override
  String toString();
}

abstract class IWalletService {
  Wallet createChildWallet({required String path});

  Uint8List signMessage({required List<int> message});
}

class WalletContext {
  const WalletContext();

  static HttpWalletService createHttpService() =>
      RustLib.instance.api.crateApiWalletWalletContextCreateHttpService();

  static List<WalletToken> getAllSupportedTokens() =>
      RustLib.instance.api.crateApiWalletWalletContextGetAllSupportedTokens();

  static List<WalletToken> getInitialSupportedTokens() => RustLib.instance.api
      .crateApiWalletWalletContextGetInitialSupportedTokens();

  static Future<double> getTokenWorth(
          {required String tokenSymbol, required double amount}) =>
      RustLib.instance.api.crateApiWalletWalletContextGetTokenWorth(
          tokenSymbol: tokenSymbol, amount: amount);

  static String hashData({required String data}) =>
      RustLib.instance.api.crateApiWalletWalletContextHashData(data: data);

  static bool verifyAccountId({required String text}) => RustLib.instance.api
      .crateApiWalletWalletContextVerifyAccountId(text: text);

  static bool verifyMnemonic({required String mnemonic}) => RustLib.instance.api
      .crateApiWalletWalletContextVerifyMnemonic(mnemonic: mnemonic);

  static bool verifyPrincipal({required String text}) => RustLib.instance.api
      .crateApiWalletWalletContextVerifyPrincipal(text: text);

  @override
  int get hashCode => 0;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WalletContext && runtimeType == other.runtimeType;
}

enum WalletTokenNetWork {
  bitcoin,
  internetComputer,
  ;
}
