/*
 * Fusion Wallet - A non-custodial cryptocurrency wallet
 * Copyright (C) 2025 Fusion Wallet
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 */


// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'http_service.dart';
import 'ic_wallet_service.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `ascii_to_hardened_derivation_path`, `from_private_key`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `CLIENT`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `deref`, `initialize`

String generateSeedPhrase() =>
    RustLib.instance.api.crateApiWalletGenerateSeedPhrase();

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Wallet>>
abstract class Wallet implements RustOpaqueInterface, IWalletService {
  @override
  Wallet createChildWallet({required String path});

  IcWalletService createIcService();

  static Wallet fromSeed({required String seedPhrase}) =>
      RustLib.instance.api.crateApiWalletWalletFromSeed(seedPhrase: seedPhrase);

  @override
  Uint8List signMessage({required List<int> message});

  String toAccountIdentifier();

  String toIcpPrincipal();
}

abstract class IWalletService {
  Wallet createChildWallet({required String path});

  Uint8List signMessage({required List<int> message});
}

class WalletContext {
  const WalletContext();

  static HttpWalletService createHttpService() =>
      RustLib.instance.api.crateApiWalletWalletContextCreateHttpService();

  static String generateAccountId(
          {required String owner, String? subaccount}) =>
      RustLib.instance.api.crateApiWalletWalletContextGenerateAccountId(
          owner: owner, subaccount: subaccount);

  static String generateIcrcAccount(
          {required String owner, String? subaccount}) =>
      RustLib.instance.api.crateApiWalletWalletContextGenerateIcrcAccount(
          owner: owner, subaccount: subaccount);

  static List<WalletToken> getAllSupportedTokens() =>
      RustLib.instance.api.crateApiWalletWalletContextGetAllSupportedTokens();

  static List<WalletToken> getInitialSupportedTokens() => RustLib.instance.api
      .crateApiWalletWalletContextGetInitialSupportedTokens();

  static Future<double> getTokenWorth(
          {required String tokenSymbol, required double amount}) =>
      RustLib.instance.api.crateApiWalletWalletContextGetTokenWorth(
          tokenSymbol: tokenSymbol, amount: amount);

  static String hashData({required String data}) =>
      RustLib.instance.api.crateApiWalletWalletContextHashData(data: data);

  static bool verifyAccount({required String text}) =>
      RustLib.instance.api.crateApiWalletWalletContextVerifyAccount(text: text);

  static bool verifyAccountId({required String text}) => RustLib.instance.api
      .crateApiWalletWalletContextVerifyAccountId(text: text);

  static bool verifyMnemonic({required String mnemonic}) => RustLib.instance.api
      .crateApiWalletWalletContextVerifyMnemonic(mnemonic: mnemonic);

  @override
  int get hashCode => 0;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WalletContext && runtimeType == other.runtimeType;
}

class WalletToken {
  final String symbol;
  final WalletTokenNetWork network;
  final String tokenAddress;
  final int? tokenDecimal;
  final String? imageUrl;
  final String tokenName;
  final String? indexCanister;
  final String? govCanister;
  final BigInt transferFee;

  const WalletToken({
    required this.symbol,
    required this.network,
    required this.tokenAddress,
    this.tokenDecimal,
    this.imageUrl,
    required this.tokenName,
    this.indexCanister,
    this.govCanister,
    required this.transferFee,
  });

  static WalletToken fromString({required String data}) =>
      RustLib.instance.api.crateApiWalletWalletTokenFromString(data: data);

  @override
  String toString() => RustLib.instance.api.crateApiWalletWalletTokenToString(
        that: this,
      );

  @override
  int get hashCode =>
      symbol.hashCode ^
      network.hashCode ^
      tokenAddress.hashCode ^
      tokenDecimal.hashCode ^
      imageUrl.hashCode ^
      tokenName.hashCode ^
      indexCanister.hashCode ^
      govCanister.hashCode ^
      transferFee.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WalletToken &&
          runtimeType == other.runtimeType &&
          symbol == other.symbol &&
          network == other.network &&
          tokenAddress == other.tokenAddress &&
          tokenDecimal == other.tokenDecimal &&
          imageUrl == other.imageUrl &&
          tokenName == other.tokenName &&
          indexCanister == other.indexCanister &&
          govCanister == other.govCanister &&
          transferFee == other.transferFee;
}

enum WalletTokenNetWork {
  bitcoin,
  internetComputer,
  ;
}
