name: Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Build SampleApplication
        run:  |
            LATEST_BUILD_TOOLS=$(ls $ANDROID_HOME/build-tools | sort -V | tail -n 1)
            ZIPALIGN="$ANDROID_HOME/build-tools/$LATEST_BUILD_TOOLS/zipalign"
    
            echo "Using zipalign from: $ZIPALIGN"