name: Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Build SampleApplication
        run:  |
            ls -a $ANDROID_HOME/build-tools/35.0.0
            zipalign.sh --no-daemon build